version: '2.1'
services:
  node:
    container_name: node
    env_file:
      - .env
    build:
      context: node
      args:
        - TZ="Europe/Czech"
    volumes:
      - ./node:/node
      - ./fuel-ui:/fuel-ui
    entrypoint: /node/entrypoint.sh
#   entrypoint: bash
    environment:
      - START_STANDALONE_SELENIUM=false
      - SELENIUM_SERVER_PORT=4444
      - SELENIUM_SERVER=selenium
      - TEST_PREFIX=test_bond*
    ports:
      - "9057"
    links:
      - selenium

  selenium:
    container_name: selenium
    build:
      context: selenium/
    env_file:
      - .env
    volumes:
      - ./selenium:/selenium
    user: seluser
    entrypoint: /selenium/entry_point.sh
    ports:
      - "4444"
