version: '2.1'
services:
  node:
    container_name: node
    user: node
    env_file:
      - .env
    build:
      context: node
      args:
        - TZ=Europe/Czech
    volumes:
      - ./node:/node
      - ./fuel-ui:/fuel-ui
    entrypoint: /node/entrypoint.sh
    environment:
      - TEST_PREFIX=${TEST_PREFIX}
    ports:
      - "9057"
    links:
      - selenium
      - share

  selenium:
    container_name: selenium
    build:
      context: selenium/
      args:
        - GECKODRIVER_VERSION=0.9.0
        - FIREFOX_VERSION=46.0
    env_file:
      - .env
    volumes:
      - ./selenium:/selenium
    user: seluser
    entrypoint: /selenium/entrypoint.sh
    ports:
      - "4444"

  share:
    container_name: share
    image: python:2.7
    volumes:
      - ./share:/share
      - ./fuel-ui:/fuel-ui
    entrypoint: /share/entrypoint.sh
    environment:
      - HTTP_PORT=8081
    ports:
      - "8081:8081"
