version: '2.1'
services:
  node:
    container_name: node
    env_file:
      - .env
    build:
      context: node
      args:
        - TZ=Europe/Czech
    volumes:
      - ./node:/node
      - ./fuel-ui:/fuel-ui
    entrypoint: /node/entrypoint.sh
#   entrypoint: bash
    environment:
      - START_STANDALONE_SELENIUM=false
      - SELENIUM_SERVER_PORT=4444
      - SELENIUM_SERVER=selenium
      - NAILGUN_PORT=8000
#      - TEST_PREFIX=test_bond*
    ports:
      - "9057"
    links:
      - selenium

  selenium:
    container_name: selenium
    build:
      context: selenium/
      args:
        - GECKODRIVER_VERSION=0.9.0
        - FIREFOX_VERSION=46.0
    environment:
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
      - NODE_REGISTER_CYCLE=5000
      - NODE_PORT=5555
    env_file:
      - .env
    volumes:
      - ./selenium:/selenium
    user: seluser
    entrypoint: /selenium/entry_point.sh
    ports:
      - "4444"
